function create(__helpers) {
  var str = __helpers.s,
      empty = __helpers.e,
      notEmpty = __helpers.ne;

  return function render(data, out) {
    out.w('<!doctype html> <html class="no-js" lang><head><meta charset="utf-8"><meta http-equiv="x-ua-compatible" content="ie=edge"><title>Multiple Graphics</title><meta name="description" content><meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no"><link rel="apple-touch-icon" href="apple-touch-icon.png"><link rel="stylesheet" href="../main.css"><script src="https://cdnjs.cloudflare.com/ajax/libs/modernizr/2.8.3/modernizr.min.js"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/detectizr/2.2.0/detectizr.min.js"></script><script src="../js/pixi.min.js"></script><script src="../js/TweenMax.min.js"></script></head><body><!--[if lt IE 8]>\n\n        <p class="browserupgrade">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>\n\n    <![endif]--><script src="../sp-framework.js"></script><script>\n\n        var maxCount = 22;\n        var count = 0;\n        var sprites, sprite;\n        var allGraphics;\n\n        function addGraphic(PIXI, input){\n\n\n            sprite = new PIXI.Sprite(allGraphics[Math.round(Math.random()*( allGraphics.length-1))] );\n\n            sprite.anchor.set(0.5);\n\n            sprite.rotation = (Math.random()*90)*4;\n\n            sprite.x = Math.random()*input.width;\n            sprite.y = Math.random()*input.height;\n\n            if(input.container.children[count])\n                input.container.removeChildAt(count);\n\n            input.container.addChildAt(sprite, count);\n\n            if(count >= maxCount) {\n                count = 0\n            } else {\n                count++;\n            };\n\n        };\n\n\n        SPF.set({\n\n            at:"back",\n\n            load: function(PIXI, input) {\n\n                allGraphics = [input.graphics.animaltech,input.graphics.bbbbird1, input.graphics.bbbbird2, input.graphics.bbbbird3, input.graphics.botanicorganic, input.graphics.handdrawnanimal1, input.graphics.handdrawnanimal2, input.graphics.handdrawnanimal3];\n\n                return allGraphics\n\n            },\n\n            init: function(PIXI, input) {\n\n\n            },\n\n            render: function(PIXI, input) {\n\n                 addGraphic(PIXI, input);\n            }\n\n        });\n\n\n\n        SPF.info({\n            debug: false,\n            title: "Multiple Graphics",\n            tip: "",\n            firstName: "Ramiro",\n            lastName: "Espada",\n            email: "re@ramiroespada.com"\n        });\n\n        SPF.start();\n\n    </script></body></html>');
  };
}
(module.exports = require("marko").c(__filename)).c(create);