function create(__helpers) {
  var str = __helpers.s,
      empty = __helpers.e,
      notEmpty = __helpers.ne;

  return function render(data, out) {
    out.w('<!doctype html> <html class="no-js" lang><head><meta charset="utf-8"><meta http-equiv="x-ua-compatible" content="ie=edge"><title>Styling</title><meta name="description" content><meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no"><link rel="apple-touch-icon" href="apple-touch-icon.png"><link rel="stylesheet" href="../main.css"><script src="https://cdnjs.cloudflare.com/ajax/libs/modernizr/2.8.3/modernizr.min.js"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/detectizr/2.2.0/detectizr.min.js"></script><script src="../js/pixi.min.js"></script><script src="../js/TweenMax.min.js"></script></head><body><!--[if lt IE 8]>\n\n        <p class="browserupgrade">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>\n\n    <![endif]--><script src="../sp-framework.js"></script><script>\n\n        var background;\n\n        SPF.set({\n\n            at:"back",\n\n            load: function(PIXI, input) {\n                return [ input.patterns.animaltech];\n            },\n\n\n            init: function(PIXI, input) {\n                background = new PIXI.extras.TilingSprite(input.patterns.animaltech, 1, 1);\n                background.anchor.set(0);\n                input.container.addChild(background);\n\n\n            },\n\n            resize:function(PIXI, input){\n                background.width = input.width;\n                background.height = input.height;\n            },\n\n            render:function(PIXI, input){\n\n                var colorFilter = new PIXI.filters.ColorMatrixFilter();\n                colorFilter.desaturate();\n\n                var vSprite = input.container.parent.children[2].children[0].children[0];\n\n\n\n                if(input.styling != null){\n\n                    if(input.styling.id == "black"){\n\n                        background.filters = [colorFilter];\n                        vSprite.filters = [colorFilter];\n                    }\n\n                    if(input.styling.id == "color"){\n\n                        background.filters = [];\n                        vSprite.filters = [];\n                    }\n\n\n                } else {\n\n                }\n\n\n            }\n\n        });\n\n\n        SPF.info({\n            debug: false,\n            title: "Styling",\n            tip: "",\n            firstName: "Ramiro",\n            lastName: "Espada",\n            email: "re@ramiroespada.com"\n        });\n\n        SPF.start("chorus1");\n\n    </script></body></html>');
  };
}
(module.exports = require("marko").c(__filename)).c(create);