var gulp     = require('gulp');
var config   = require('./config');
var swig     = require('gulp-swig');
var rename   = require('gulp-rename');

module.exports = function(codepoints) {
    console.log("...with "+codepoints.length+" svg files");
  gulp.src(config.template)
    .pipe(swig({
      data: {
        icons: codepoints.map(function(icon) {
          return {
            name: icon.name,
            code: icon.unicode[0].charCodeAt(0).toString(16).toUpperCase()
          }
        }),

        fontName: config.options.fontName,
        fontPath: config.fontPath,
        className: config.className,
        comment: '!!!  DO NOT EDIT DIRECTLY  !!!\nGenerated by gulp/tasks/iconFont.js\nfrom ' + config.template
      }
    }))
    .pipe(rename(config.sassOutputName))
    .pipe(gulp.dest(config.sassDest));
};
